services:
  - icon: bi bi-person-walking
    title: Visit RS GOLD
    description: Bring your gold or silver items to our branch for secure and private evaluation.
    delay: 100

  - icon: bi bi-card-checklist
    title: Quick KYC Verification
    description: Share valid ID and basic proof documents to complete a compliant transaction.
    delay: 200

  - icon: bi bi-cpu
    title: XRF Purity Testing
    description: We perform computerised purity testing for accurate valuation without damage.
    delay: 300

  - icon: bi bi-calculator
    title: Transparent Valuation
    description: You get a clear quotation based on purity, net weight, and live market price.
    delay: 400

  - icon: bi bi-bank
    title: Pledged Gold Release
    description: We settle remaining dues and assist in releasing pledged gold from banks and lenders.
    delay: 500

  - icon: bi bi-cash-stack
    title: Instant Payment
    description: Receive spot cash or bank transfer through IMPS, NEFT, RTGS, or UPI.
    delay: 600

call-to-action:
  image: assets/img/cta-bg.jpg
  title: Documents Required
  description: Carry the required documents for faster processing.
  button_text: Call RS GOLD
  button_link: tel:+919885975975

contact:
  title: Contact
  subtitle: Need a Quick Valuation?
  description: Reach RS GOLD

  info1: Address
  address_line1: Plot No. 69, 1st Floor, Opposite Babai Hotel
  address_line2: Sai Ram Colony, Puppalguda, Manikonda, Hyderabad

  info2: Call Us
  phone: "+91 98859 75975"
  phone_alt: "+91 98482 28229"

  info3: WhatsApp
  email: "+91 98859 75975"
  email_alt: "Fast response for gold price queries"

  info4: Open Hours
  week: Monday - Sunday
  time: 9:00 AM - 9:00 PM

form_action: "#"

social_links:
  - platform: whatsapp
    url: "https://wa.me/919885975975"
  - platform: instagram
    url: "#"
  - platform: facebook
    url: "#"

useful_links:
  - title: Home
    url: "#hero"
  - title: About
    url: "#about"
  - title: Process
    url: "#services"
  - title: Documents
    url: "#call-to-action"
  - title: Contact
    url: "#contact"

branches:
  - Gold Buying
  - Silver Buying
  - Pledged Gold Release
  - XRF Purity Testing

newsletter:
  description: "Call us for live gold rates and same-day transactions."
  form_action: "#"

brand:
  logo: "/assets/img/logo.png"
  logo_alt: "RS GOLD Logo"

whatsapp:
  number: "919885975975"
  text: "Hello RS GOLD, I want today's gold rate and valuation details."

live_rates:
  title: Live Gold & Silver Rate
  subtitle: Hyderabad / India
  description: Real-time indicative rates in INR. Final branch valuation may vary by purity and item condition.

locations:
  title: Our Stores
  subtitle: Visit
  description: RS GOLD Branches
  items:
    - name: RS GOLD
      short_address: Puppalguda, Manikonda, Hyderabad
      full_address: Plot No. 69, 1st Floor, Opposite Babai Hotel, Sai Ram Colony, Puppalguda, Manikonda, Hyderabad
      map_link: "https://maps.app.goo.gl/5c4hVzdQzCEyYTSr8"
      embed_query: "17.4008563,78.3885581"
    - name: RS GOLD LANCOHILLS
      short_address: Lanco Hills, Hyderabad
      full_address: RS GOLD LANCOHILLS, Hyderabad
      map_link: "https://maps.app.goo.gl/gMRWKzMjmmVmvNBD6"
      embed_query: "17.4072329,78.3796698"
